version: '3.4'
services:

  customer-api-gw:
    image: customer-api-gateway:latest
    container_name: customer-api-gw
    hostname: customer-api-gw
    environment:
      logging.config: classpath:logback-classic.xml
      oauth.clientId: NUM
      oauth.clientSecret: 1288392-192982-377283-282873
      oauth.checkTokenUri: http://auth-server:8080/oauth/check_token
    ports:
      - 8080:8080

  java-interpreter-server:
    image: java-interpreter-server:latest
    container_name: java-interpreter
    hostname: java-interpreter
    ports:
      - 8081:8080
